### Endpoint de teste
GET http://localhost:3003/ping

### Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "nickname": "yuzo",
    "email": "yuzo@email.com",
    "password": "abc123"
}

### Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}


### Get all recipes by name
GET http://localhost:3003/recipes/?name=bife
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJiOWI3ZWU4LWFlNGItNGJkMS05YmQ2LWU3ZTIxNTk0Mzk5YiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1OTU1NjIxOSwiZXhwIjoxNjU5NjQyNjE5fQ.6z50S2CPR1UCGKiljnLgh37TIsyMO0j0LkOJXfYJM8o

### Get all recipes 
GET http://localhost:3003/recipes/
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJiOWI3ZWU4LWFlNGItNGJkMS05YmQ2LWU3ZTIxNTk0Mzk5YiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1OTU1NjIxOSwiZXhwIjoxNjU5NjQyNjE5fQ.6z50S2CPR1UCGKiljnLgh37TIsyMO0j0LkOJXfYJM8o