### Endpoint de teste
GET http://localhost:3003/ping


### Signup
POST http://localhost:3003/signup
Content-Type: application/json

{
    "nickname": "larissa",
    "email": "lari@dev.com",
    "password": "mega-segura"    
}

### Login
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "lari@dev.com",
    "password": "mega-segura"
}


### Get all users (protected)
GET http://localhost:3003/users?search=
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM0NzEwZDhlLWIxZjYtNGQyNS05OTM1LTg1ZGE3MWQwNTI4OCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTk0Njg1OTksImV4cCI6MTY1OTU1NDk5OX0.ZYXI_rXfiLZEkbmbIWySSp8KeIxS5rVsxEdMSHRAjtY

### Edit user (protected)
PUT http://localhost:3003/users/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM0NzEwZDhlLWIxZjYtNGQyNS05OTM1LTg1ZGE3MWQwNTI4OCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTk0NjkwNTYsImV4cCI6MTY1OTU1NTQ1Nn0.7DdLkOwE_D5P6HhXUl5YVEYaOv-ydMycf4EHJL3rzew
Content-Type: application/json

{
    "nickname": "zoyu"
}

### Delete user (protected)
DELETE http://localhost:3003/users/6968c075-fb25-40c0-b356-e8bf197216c4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcwNzliOGU0LTk1Y2QtNDhhYS04MmE5LTc3NDU0ZTk0Yjc4OSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1OTQ2ODA2MCwiZXhwIjoxNjU5NTU0NDYwfQ.vezrrgaIl-39T2e6amXHE5AvGCtgFBdwj8tYEdNKgQw
