### Endpoint de teste
GET http://localhost:3003/ping

###Exercício 1 
POST http://localhost:3003/users
Content-Type: application/json

{
    "nickname":"lari",
    "email":"larissa@dev.com",
    "password":"senha-forte-sqn"
}

###Exercício 2
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email":"larissa@dev.com",
    "password":"senha-forte-sqn"
}

###Exercício 3
GET http://localhost:3003/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI3YzYzNWQwLTAwZDEtNGRhYi04MWY0LWY2OTFmZjNkYzk0OCIsImlhdCI6MTY1OTM4MTE4NywiZXhwIjoxNjU5NDY3NTg3fQ.ko98n4BQELKuzCzAgyQM6Ml3ayGcSZc5-RbuK_M_k1c
Content-Type: application/json

{
    "email":"larissa@dev.com",
    "password":"senha-forte-sqn"
}

###Exercício 4
PUT  http://localhost:3003/users/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxMWQ3ODA5LTk4NWEtNDhjYS1hZTNlLWQ4YWIxZjZkMmFiNyIsImlhdCI6MTY1OTM4MzUwMywiZXhwIjoxNjU5NDY5OTAzfQ.O5NGf0-wqOs3px150qc-RVpDEFSwfhfkFhXsJyYVVcg
Content-Type: application/json

{
    "nickname":"larissa",
    "email":"larissa@devmail.com",
    "password":"mega-segura-sqn"
}

### Exercício 5
DELETE  http://localhost:3003/users/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxMWQ3ODA5LTk4NWEtNDhjYS1hZTNlLWQ4YWIxZjZkMmFiNyIsImlhdCI6MTY1OTM4MzUwMywiZXhwIjoxNjU5NDY5OTAzfQ.O5NGf0-wqOs3px150qc-RVpDEFSwfhfkFhXsJyYVVcg
Content-Type: application/json

{
    "userId":"011d7809-985a-48ca-ae3e-d8ab1f6d2ab7" 
}
