### Endpoint de teste
GET http://localhost:3003/ping

### 1) Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Beltrano",
    "email": "beltrano@gmail.com",
    "password": "abc123"
}

### 2) Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}

### 3) Get users
GET http://localhost:3003/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJiOWI3ZWU4LWFlNGItNGJkMS05YmQ2LWU3ZTIxNTk0Mzk5YiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDA0MjM5MywiZXhwIjoxNjYwMTI4NzkzfQ.ya2CQFRF2kWpKCpa6rE8pPm2EBtblU_LXha3ks6VuC0

### 3) Delete user
DELETE http://localhost:3003/users/ac878d66-838c-46af-98a2-1806f0beb623
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJiOWI3ZWU4LWFlNGItNGJkMS05YmQ2LWU3ZTIxNTk0Mzk5YiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDA0MjM5MywiZXhwIjoxNjYwMTI4NzkzfQ.ya2CQFRF2kWpKCpa6rE8pPm2EBtblU_LXha3ks6VuC0