### Endpoint de teste
GET http://localhost:3003/ping

### Endpoint teste 2 - get all classes

GET http://localhost:3003/classrooms

### Endpoint 1
POST http://localhost:3003/classrooms
Content-Type: application/json

{
    "name": "teste-turma",
    "module": "2"
}

### Endpoint 2 - buscar turmas ativas 
GET http://localhost:3003/classrooms/active


### Endpoint 3 - mudar turma de módulo
PUT  http://localhost:3003/classrooms/103/module
Content-Type: application/json

{
    "module": "4"
}

### Endpoint teste - get all students
GET http://localhost:3003/students

### Endpoint 4 - criar estudante

POST http://localhost:3003/students
Content-Type: application/json

{
    "name": "Larissa",
    "email": "larissa@mail.com",
    "birthdate":"1993-11-22",
    "classroom_id":"101"
}

### Endpoint 5 - buscar estudante por nome
GET http://localhost:3003/students/searchByName
Content-Type: application/json

{ 
 "name":"Ada"
}

### Endpoint 6 - editar estudante de turma
PUT  http://localhost:3003/students/204/classroom
Content-Type: application/json

{
    "classroom_id": "103"
}

### Endpoint 7 - estudantes por turma
GET http://localhost:3003/students/103
