### Endpoint de teste
GET http://localhost:3003/ping

### Endpoint teste 2

GET http://localhost:3003/classrooms

### Endpoint 1
POST http://localhost:3003/classrooms
Content-Type: application/json

{
    "name": "teste-turma",
    "module": 1
}