### Endpoint de teste
GET http://localhost:3003/ping

### 1) Endpoint 1 - Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Larissa",
    "email": "larissa@devemail.com",
    "password": "abc123"
}


### 2) Endpoint 2 - Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}


### 3) Endpoint 3 - Criar Post
POST http://localhost:3003/posts/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmOGJjOWM1LTRhOTAtNDQxYi1hNzAzLTJiMzg3NTQzZWZlNiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjA0MTI1NzUsImV4cCI6MTY2MDQ5ODk3NX0.oI0uae9ug5sOOK0pkKGxjAAqep8t_fhg5kCXAzoPTT4
Content-Type: application/json

{
    "content": "Finalizando projeto da semana da Labenu :)"
}


### 4) Endpoint 4 - Lista de Posts
GET http://localhost:3003/posts/
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmOGJjOWM1LTRhOTAtNDQxYi1hNzAzLTJiMzg3NTQzZWZlNiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjA0MTI1NzUsImV4cCI6MTY2MDQ5ODk3NX0.oI0uae9ug5sOOK0pkKGxjAAqep8t_fhg5kCXAzoPTT4


### 5) Endpoint 5 - Deletar Post
DELETE http://localhost:3003/posts/delete/202
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmOGJjOWM1LTRhOTAtNDQxYi1hNzAzLTJiMzg3NTQzZWZlNiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjA0MTI1NzUsImV4cCI6MTY2MDQ5ODk3NX0.oI0uae9ug5sOOK0pkKGxjAAqep8t_fhg5kCXAzoPTT4


### 6) Endpoint 6 - Curtir Post
POST http://localhost:3003/posts/like/588fb6bc-b579-4846-a088-e59fd0f0cafe
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDQxMjg4MywiZXhwIjoxNjYwNDk5MjgzfQ.7nEdnmhKeAFjre01Vl76yecLX9l4CPWrt9jVboi1mPw


### 7) Endpoint 7 - Descurtir Post
POST http://localhost:3003/posts/dislike/588fb6bc-b579-4846-a088-e59fd0f0cafe
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmOGJjOWM1LTRhOTAtNDQxYi1hNzAzLTJiMzg3NTQzZWZlNiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjA0MTI1NzUsImV4cCI6MTY2MDQ5ODk3NX0.oI0uae9ug5sOOK0pkKGxjAAqep8t_fhg5kCXAzoPTT4
