### Endpoint de teste
GET http://localhost:3003/ping

### 1) Endpoint 1 - Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Larissa",
    "email": "larissa@mail.com",
    "password": "abc123"
}

### 2) Endpoint 2 - Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "larissa@mail.com",
    "password": "abc123"
}

### 3) Endpoint 3 - Criar Post

POST http://localhost:3003/posts/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA2ZGI4NzJmLTIyNTMtNGYyZi05ZTVmLWFjN2E5ZTlmODJiMiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjAzMjQwMjIsImV4cCI6MTY2MDQxMDQyMn0.Dal4R06_FQp6e8tGReeCeTX40beVDaxA1jLCVinyjYY
Content-Type: application/json

{
    "content": "Olá, mundo!"
}

### 4) Endpoint 4 - Lista de Posts
GET http://localhost:3003/posts/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA2ZGI4NzJmLTIyNTMtNGYyZi05ZTVmLWFjN2E5ZTlmODJiMiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjAzMjQwMjIsImV4cCI6MTY2MDQxMDQyMn0.Dal4R06_FQp6e8tGReeCeTX40beVDaxA1jLCVinyjYY