### Endpoint de teste
GET http://localhost:3003/ping

### 1) Endpoint 1 - Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Larissa",
    "email": "larissa@mail.com",
    "password": "abc123"
}

### 2) Endpoint 2 - Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}

### 3) Endpoint 3 - Criar Post

POST http://localhost:3003/posts/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDMzNDA5NSwiZXhwIjoxNjYwNDIwNDk1fQ.z92QDafTMKaMPW6apxMGfChtn9Plq6rfSsu8uKEhBU8
Content-Type: application/json

{
    "content": "Olá, mundo! / Hello!"
}

### 4) Endpoint 4 - Lista de Posts
GET http://localhost:3003/posts/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDMzMTA0MSwiZXhwIjoxNjYwNDE3NDQxfQ.TNy1P71m5Ow3SVNayS4QIshJ3GYl5S5pwgBiBLmGLg8

### 5) Endpoint 5 - Deletar Post
DELETE http://localhost:3003/posts/delete/202
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDMzMTA0MSwiZXhwIjoxNjYwNDE3NDQxfQ.TNy1P71m5Ow3SVNayS4QIshJ3GYl5S5pwgBiBLmGLg8

### 6) Endpoint 6 - Curtir Post
POST http://localhost:3003/posts/like/0bdcc932-4868-4184-ae6b-d2ca8decb05e
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDMzNTQ2NiwiZXhwIjoxNjYwNDIxODY2fQ.YipFJ05zoVNJzc2oRK0whLH0ZO-xq7P_o6mnUQq2AkU