### Ping
GET http://localhost:3003/ping

### Create Perfume
POST http://localhost:3003/perfumes

### Get all perfumes order by name and sort id descending
GET http://localhost:3003/perfumes?q=armani&sort=id&order=desc

### Get all perfumes order by price descending
GET http://localhost:3003/perfumes

### Get all perfumes order by brand
GET http://localhost:3003/perfumes?q=armani