### Endpoint de teste
GET http://localhost:3003/ping

### Endpoint de criação de usuário

POST http://localhost:3003/users
Content-Type: application/json

{
    "email": "testes@email.com",
    "password":"senha123"
}

### Busca por todos os usuários
GET http://localhost:3003/users

### também é possível buscar pelo email, ordenado por id
GET http://localhost:3003/users?q=gmail&sort=id&order=asc

### Endpoint de cadastro de produto
POST http://localhost:3003/products
Content-Type: application/json

{

    "name": "Monitor Ultra",
    "price":750

}


### Busca por todos os produtos
GET http://localhost:3003/products

### também é possível buscar pelo nome, ordenado por price em ordem (de)crescente 
GET http://localhost:3003/products?q=monitor&sort=price&order=desc
