### Endpoint de teste
GET http://localhost:3003/ping

### 1) Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Larissa",
    "email": "larissa@dev.com",
    "password": "backend"
}

### 2) Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}

### 3) Add Product
POST http://localhost:3003/products/add
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MTUzNzczMSwiZXhwIjoxNjYxNjI0MTMxfQ.IYHtJgIr_SaNlp4niw6rE3kQCT9K-PmOtiSpET-v75M
Content-Type: application/json

{
    "id": 8300,
    "name": "VESTIDO MALHA COM FENDA"
}

### 4) Get Products
GET http://localhost:3003/products/

### 4) Get Products By Search / id
GET http://localhost:3003/products/searchId/8360

### 5) Get Products By Search / name
GET http://localhost:3003/products/searchName?search=com

### 6) Get Products By Search / Tag
GET http://localhost:3003/products/byTag?search=metal

