### Endpoint de teste
GET http://localhost:3003/ping

### 1) Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Larissa",
    "email": "larissa@dev.com",
    "password": "backend"
}

### 2) Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}

### 3) Create Show
POST http://localhost:3003/shows/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDg0Mzc2NSwiZXhwIjoxNjYwOTMwMTY1fQ.Aoyv7z6ba6BGXxK8LH7HEHd73rwAgvvkdHx3cnXu-JE
Content-Type: application/json

{
    "band":"Daisy Jones & The Six",
    "starts_at":"2022-12-12"
}

### 4) Get Shows
GET http://localhost:3003/shows/

### 5) Ticket Reservation
POST http://localhost:3003/shows/tickets/2d7ddda0-8d61-4eb7-ad92-4d547d8dfe87
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMxM2M1MjAxLTY5NTYtNGM5Yy04ZGI1LWRmNDA3NmEzNWIxMiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjA4NDQ1MjcsImV4cCI6MTY2MDkzMDkyN30.mkqOvbB3-5bnjoQykdyC-jiTaKtQv9ndDWtgOa18dIo
